name: Deploy

on:
  push:
    branches:
      - production
  pull_request:
    types:
      - closed
    branches:
      - production

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/stock-watcher-api
            git pull origin production
            npm install
            npm run migrate
            npm run build
            pm2 reload market-trend
